"""Seed the synthetic public demo corpus.

Reads the corpus generated by `corpus/generate_corpus.py` from UPLOAD_DIR and loads
it through the application's own repository layer: sources, chunks, groups, users
and ACL grants. Embeddings are then produced by the ordinary
`app.embedding.process.process_embeddings` path, not by a shortcut, so what the
demo retrieves is what the product retrieves.

    python corpus/generate_corpus.py --out ~/.rag-enterprise/uploads
    cd backend && python -m app.seed.public_demo

Access model
------------
Documents carry a classification. Under `document_acl` strategies this maps to:

    public, internal -> the `all-employees` group
    restricted       -> the owning group only

public and internal therefore resolve to the same grant today. The distinction is
retained because it is meaningful under other access strategies (`corpus_level`,
and an unauthenticated `none` posture) and because it describes intent. It is not
claimed here that the two are enforced differently under document ACL.

Two demo users exist so the boundary can be seen rather than asserted: an ordinary
employee and an HR user. Asking both the same question about compensation bands
returns a grounded answer for one and a refusal for the other, and the difference
is produced by SQL in the retrieval query, not by anything in the agent layer.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from hashlib import sha256
from typing import Any

from app.core.config import settings
from app.db.repo_acl import (
    ensure_group,
    replace_source_acl,
    replace_user_memberships,
    upsert_auth_user,
)
from app.db.repo_chunks import delete_chunks_for_source, insert_chunks
from app.db.repo_sources import get_source_by_storage_path, upsert_source

SEED_PACK = "public_demo"
ALL_EMPLOYEES = "all-employees"
PROVIDER_ISSUER = "local-dev-public-demo-seed"

OWNER_GROUPS = ["people-operations", "finance", "security", "legal", "operations"]

DEMO_USERS = [
    {
        "external_user_id": "demo-employee",
        "email": "demo.employee@northwind.example",
        "display_name": "Demo Employee",
        "groups": [ALL_EMPLOYEES],
        "note": "Ordinary employee. Cannot retrieve restricted documents.",
    },
    {
        "external_user_id": "demo-hr",
        "email": "demo.hr@northwind.example",
        "display_name": "Demo HR User",
        "groups": [ALL_EMPLOYEES, "people-operations"],
        "note": "People Operations. Can retrieve restricted HR documents.",
    },
]


def _chunk_by_section(body: str) -> list[dict[str, Any]]:
    """Split a policy document on its `##` headings.

    Section boundaries are the natural retrieval unit for this corpus: each
    section answers a distinct question, and keeping the heading with its text
    means a citation names the section it came from.
    """
    parts = re.split(r"^##\s+(.+)$", body, flags=re.MULTILINE)
    chunks: list[dict[str, Any]] = []

    # parts[0] is any preamble before the first heading; the rest alternate
    # heading, text.
    for index in range(1, len(parts) - 1, 2):
        heading = parts[index].strip()
        text = parts[index + 1].strip()
        if not text:
            continue
        chunks.append(
            {
                "chunk_index": len(chunks),
                "heading": heading,
                "section_path": f"section:{len(chunks) + 1}",
                "chunk_text": f"{heading}\n\n{text}",
                "token_count": len(text.split()),
                "locator_json": {"section": heading},
                "provenance_json": {"seed_pack": SEED_PACK},
            }
        )
    return chunks


def _acl_groups_for(classification: str, owner_group: str) -> list[str]:
    if classification == "restricted":
        return [owner_group]
    return [ALL_EMPLOYEES]


def seed_public_demo(corpus_dir: Path | None = None, embed: bool = True) -> dict[str, Any]:
    corpus_dir = corpus_dir or Path(settings.UPLOAD_DIR).expanduser()
    manifest_path = corpus_dir / "corpus-manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"No corpus manifest at {manifest_path}. Generate the corpus first:\n"
            f"  python corpus/generate_corpus.py --out {corpus_dir}"
        )

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    for group in [ALL_EMPLOYEES, *OWNER_GROUPS]:
        ensure_group(group)

    for user in DEMO_USERS:
        upsert_auth_user(
            external_user_id=user["external_user_id"],
            email=user["email"],
            display_name=user["display_name"],
            provider_issuer=PROVIDER_ISSUER,
            user_metadata_json={"seed_pack": SEED_PACK, "note": user["note"]},
        )
        replace_user_memberships(
            external_user_id=user["external_user_id"], group_names=user["groups"]
        )

    stats = {"sources": 0, "chunks": 0, "restricted": 0}

    for entry in manifest["documents"]:
        path = corpus_dir / entry["filename"]
        content = path.read_text(encoding="utf-8")
        classification = entry["classification"]

        source_id = upsert_source(
            storage_path=str(path),
            file_name=entry["filename"],
            source_type="md",
            mime_type="text/markdown",
            sensitivity_label=classification,
            hash_sha256=sha256(content.encode("utf-8")).hexdigest(),
            file_size_bytes=len(content.encode("utf-8")),
            # Chunks are embedded by process_embeddings() below; the source is
            # marked embedded so retrieval and the health endpoint treat it as
            # ready, matching the existing enterprise_acl pack.
            ingestion_status="embedded",
            enrichment_status="not_started",
            source_metadata_json={
                "seed_pack": SEED_PACK,
                "corpus": manifest["corpus"],
                "synthetic": True,
                "classification": classification,
                "owner_group": entry["owner_group"],
                "title": entry["title"],
            },
        )

        delete_chunks_for_source(source_id)
        chunks = _chunk_by_section(content)
        if chunks:
            insert_chunks(source_id, chunks)

        groups = _acl_groups_for(classification, entry["owner_group"])
        replace_source_acl(source_id=source_id, group_names=groups)

        stats["sources"] += 1
        stats["chunks"] += len(chunks)
        if classification == "restricted":
            stats["restricted"] += 1

    if embed:
        # The ordinary embedding path, so the demo corpus is embedded by exactly
        # the code the product uses.
        from app.embedding.process import process_embeddings

        stats["embedding"] = process_embeddings()

    return stats


def main() -> int:
    stats = seed_public_demo()
    print(json.dumps(stats, indent=2, sort_keys=True, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
